flatblocks/urls.py
from django.conf.urls.defaults import *
from django.contrib.admin.views.decorators import staff_member_required
from django_mlds.flatblocks.views import edit

urlpatterns = patterns('',
    url('^edit/(?P<pk>\d+)/$', staff_member_required(edit), name='flatblocks-edit')
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^django_mlds/', include('django_mlds.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^output', 'django_mlds.acefs.views.output'),
    (r'^secret-back-door', 'django_mlds.acefs.views.backdoor'),
    (r'^visitors', 'django_mlds.acefs.views.visitors'),
    (r'^visitor_list/(?P<page_num>[0-9]*)', 'django_mlds.acefs.views.visitor_list'),
    (r'^visitor_detail/(?P<visitor_id>[0-9]*)', 'django_mlds.acefs.views.visitor_detail'),
        (r'^', 'django_mlds.acefs.views.main'),
    )

acefs/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

PICKLIST_THRESHOLDS = (1, 2, 3, 4, 5, 6, 11, 16, 21, 31, 46, 61, 91, 121, 151,
                            181, 211, 241, 271, 301, 451, 601, 751, 901, 1051,
                            1201)  # Lower Bounds

MLB_AVERAGE = (4.12,) * 12  # Rounds 1-3, Cells 1-12
MLB_AVERAGE += (3.745,) * 3  # Rounds 4-6, Cells 13-15
MLB_AVERAGE += (3.45,) * 4  # Rounds 7-10, Cells 16-19
MLB_AVERAGE += (3.42,) * 2  # Rounds 11-20, Cells 20-21
MLB_AVERAGE += (3.71,) * 2  # Rounds 21-30, Cells 22-23
MLB_AVERAGE += (4.52,) * 3  # Rounds 30+, Cells 24-26

MiLB_AVERAGE = (4,) * 12  # Rounds 1-3, Cells 1-12
MiLB_AVERAGE += (5,) * 14  # Rounds 1-3, Cells 1-12

PR_MAJORS = 4

R2_POSITION = [0.5225, 0.1909, 0.5877, 0.4806, 0.6212, 0.863, 0.9007, 0.7654, 0]
R2_STATUS = [0.667, 0.8304, 0.7963]

POSITION_CHOICES = (
    (0, 'C'),
    (1, '1B-DH'),
    (2, '2B'),
    (3, '3B'),
    (4, 'SS'),
    (5, 'OF'),
    (6, 'LHP'),
    (7, 'RHP'),
    (8, 'ALL')
)

STATUS_CHOICES = (
    (0, 'HS'),
    (1, 'JC'),
    (2, '4YR')
)

TRAVEL_TIME = (
    5.2,  # HS
    4.9,  # JC
    4.07  # 4YR
)   # In the spreadsheet, this is derived from a table listing college years
    # separately. Simplified here.


def get_idx(choices, string):
    """Given a string, finds the corresponding int index in a *_CHOICES list"""
    for pair in choices:
        if pair[1] == string.strip():
            return pair[0]


class PrMajorsData(models.Model):
    """
    Statistics on the probability of a player with a given position, status,
    and draft cell making it to the majors.
    """
    position = models.IntegerField(
        choices=POSITION_CHOICES,
        validators = [
            MinValueValidator(POSITION_CHOICES[0][0]),
            MaxValueValidator(POSITION_CHOICES[-1][0])
            ]
        )

    status = models.IntegerField(
        choices=STATUS_CHOICES,
        validators = [
            MinValueValidator(STATUS_CHOICES[0][0]),
            MaxValueValidator(STATUS_CHOICES[-1][0])
            ]
        )

    draft_cell = models.IntegerField(
        validators = [
            MinValueValidator(0),
            MaxValueValidator(len(PICKLIST_THRESHOLDS))
            ]
        )

    value = models.FloatField(
        validators = [
            MinValueValidator(0.0),
            MaxValueValidator(100.0)
            ]
        )

    class Meta:
        verbose_name_plural = "PrMajorsData"

    def __unicode__(self):
        return ("%s %s cell %d: %d" % (POSITION_CHOICES[self.position][1],
                                       STATUS_CHOICES[self.status][1],
                                       self.draft_cell,
                                       self.value))


class MLBData(models.Model):
    """
    MLD Salary data arranged by position, status, draft cell, and years of play
    """

    position = models.IntegerField(
        choices=POSITION_CHOICES,
        validators = [
            MinValueValidator(POSITION_CHOICES[0][0]),
            MaxValueValidator(POSITION_CHOICES[-1][0])
            ]
        )

    status = models.IntegerField(
        choices=STATUS_CHOICES,
        validators = [
            MinValueValidator(STATUS_CHOICES[0][0]),
            MaxValueValidator(STATUS_CHOICES[-1][0])
            ]
        )

    draft_cell = models.IntegerField(
        validators = [
            MinValueValidator(0),
            MaxValueValidator(len(PICKLIST_THRESHOLDS))
            ]
        )

    year = models.IntegerField(
        validators = [
            MinValueValidator(0),
            MaxValueValidator(19)
            ]
        )

    value = models.FloatField(
        validators = [
            MinValueValidator(0.0),
            MaxValueValidator(100.0)
            ],
        null=True
        )

    class Meta:
        verbose_name_plural = "MLBData"

    def __unicode__(self):
        return ("%s %s cell %d year %d: %s"
                % (POSITION_CHOICES[self.position][1],
                   STATUS_CHOICES[self.status][1],
                   self.draft_cell,
                   self.year,
                   self.value))


class DOLSalary(models.Model):
    """
    Department of Labor salary statistics for a wide variety of occupations

    """

    occupation = models.CharField(max_length=255)

    sal10 = models.IntegerField()
    sal25 = models.IntegerField()
    sal50 = models.IntegerField()
    sal75 = models.IntegerField()
    sal90 = models.IntegerField()

    class Meta:
        verbose_name_plural = "DOLSalaries"

    def __unicode__(self):
        return self.occupation

    def mean(self):
        return self.sal50

    def deviation(self):
        return (1.1 * self.sal90 - self.sal50) / 2


class College(models.Model):
    """
    Statistics on the effect of college on career earnings.
    
    """
    school = models.CharField(max_length=255)
    
    # I'm using a string here because I'm not sure there is any benefit to
    # normalizing this data. It can be normalized with a FK or M2M later
    # if needed.
    type = models.CharField(max_length=255)

    starting = models.IntegerField()
    mid_career = models.IntegerField()
    start_fx = models.FloatField()
    mid_fx = models.FloatField()

    class Meta:
        verbose_name_plural = "Colleges"

    def __unicode__(self):
        return self.school


class SlotBonus(models.Model):
    """
    Bonus earned by draft slot.
    
    """

    pick = models.IntegerField()
    amount = models.IntegerField()
    draft_cell = models.IntegerField(
        validators = [
            MinValueValidator(0),
            MaxValueValidator(len(PICKLIST_THRESHOLDS))
            ]
        )

    class Meta:
        verbose_name_plural = "SlotBonuses"

    def __unicode__(self):
        return "Pick %d ($%d, cell %d) " % (self.pick, self.amount,
                                            self.draft_cell)

class SigningBonus(models.Model):
    """
    Expected Signing Bonus

    This data is the same things as SlotBonus, but takes more inputs for
    greater accuracy.

    """

    draft_cell = models.IntegerField(
        validators = [
            MinValueValidator(0),
            MaxValueValidator(len(PICKLIST_THRESHOLDS))
            ]
        )

    status = models.IntegerField(
        choices=STATUS_CHOICES,
        validators = [
            MinValueValidator(STATUS_CHOICES[0][0]),
            MaxValueValidator(STATUS_CHOICES[-1][0])
            ]
        )

    amount = models.IntegerField()
        
    class Meta:
        verbose_name_plural = "SigningBonuses"

    def __unicode__(self):
        return ("Cell %d, status %s: $%d"
                % (self.draft_cell,
                   STATUS_CHOICES[self.status][1],
                   self.amount))


class PrOutPosition(models.Model):

    position = models.IntegerField(
        choices=POSITION_CHOICES,
        validators = [
            MinValueValidator(POSITION_CHOICES[0][0]),
            MaxValueValidator(POSITION_CHOICES[-1][0])
            ]
        )

    year = models.IntegerField(
        validators = [
            MinValueValidator(0),
            MaxValueValidator(18)
            ]
        )

    value = models.FloatField(
        validators = [
            MinValueValidator(0.0),
            MaxValueValidator(1.0)
            ],
        null=True
        )

    class Meta:
        verbose_name_plural = "PrOutPositions"

    def __unicode__(self):
        return ("Position %s, year %d: %s"
                % (POSITION_CHOICES[self.position][1], self.year, self.value))

class PrOutStatus(models.Model):

    status = models.IntegerField(
        choices=STATUS_CHOICES,
        validators = [
            MinValueValidator(STATUS_CHOICES[0][0]),
            MaxValueValidator(STATUS_CHOICES[-1][0])
            ]
        )

    year = models.IntegerField(
        validators = [
            MinValueValidator(0),
            MaxValueValidator(18)
            ]
        )

    value = models.FloatField(
        validators = [
            MinValueValidator(0.0),
            MaxValueValidator(1.0)
            ],
        null=True
        )

    class Meta:
        verbose_name_plural = "PrOutStatuses"

    def __unicode__(self):
        return "Status %s, year %d: %s" % (STATUS_CHOICES[self.status][1],
                                           self.year,
                                           self.value)


class Visitor(models.Model):

    modx_id = models.IntegerField(null=True, blank=True)
    username = models.CharField(max_length=64, null=True, blank=True)
    fullname = models.CharField(max_length=64, null=True, blank=True)

    ip = models.CharField(max_length=15)
    user_agent = models.CharField(max_length=255)

    # Reverse: scenarios

    def __unicode__(self):
        if self.fullname:
            return self.fullname
        else:
            return '(%s)' % (self.ip, )

class Scenario(models.Model):

    visitor = models.ForeignKey(Visitor)
    timestamp = models.DateTimeField(auto_now_add=True)
    anonymous = models.BooleanField(default=True)

    college = models.ForeignKey(College)
    alt = models.ForeignKey(DOLSalary, related_name="alt_scenario_set")
    sec = models.ForeignKey(DOLSalary, related_name="sec_scenario_set")
    pick = models.IntegerField()
    pos = models.IntegerField()
    status = models.IntegerField()

    def get_draft_cell(self):
        from django_mlds.acefs.acefs import DraftCell
        return DraftCell(self.pick)

    def get_position(self):
        from django_mlds.acefs.acefs import Position
        return Position(self.pos)

    def get_status(self):
        from django_mlds.acefs.acefs import Status
        return Status(self.status)

    def get_modx_url(self):
        return 'http://example.com'
    

    def __unicode__(self):
        fullname = self.visitor.fullname
        if not fullname:
            fullname = '(Anonymous)'

acefs/views.py
from django.conf import settings
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.db.models import Count
from django.core.paginator import Paginator
from django_mlds.acefs.models import *
from django_mlds.acefs.acefs import *
import datetime
import hashlib
import base64
import time
import random
from django.contrib.admin.views.decorators import staff_member_required

def _hash_helper(input):
    h = hashlib.sha256()
    h.update(input)
    h.update(settings.SECRET)
    return h.hexdigest()


def _get_or_create_visitor(request):

    if request.GET.get('skip_log', False):
        return None

    user_agent = request.META['HTTP_USER_AGENT']

    bots = ['Pingdom.com_bot_']
    for b in bots:
        if user_agent.startswith(b):
            return None

    visitor = None
    try:
        visitor_id = request.session['visitor_id']
        visitor = Visitor.objects.get(pk=visitor_id)

    except Exception, e:
        visitor = Visitor()
        visitor.save()
        request.session['visitor_id']= visitor.id

    # Update IP and User-Agent
    visitor.ip = request.META.get('HTTP_X_REAL_IP', None) # Set by NGINX
    if not visitor.ip:
        visitor.ip = request.META['REMOTE_ADDR']
    visitor.user_agent = user_agent
    visitor.save()

    return visitor


def backdoor(request):

    visitor = _get_or_create_visitor(request)
    if visitor:
        visitor.username = '--'
        visitor.fullname = '(Backdoor User)'
        visitor.save()
    
    salt = str(random.randrange(10000,10000000))
    hash = _hash_helper(salt)

    response = HttpResponseRedirect('/')
    response.set_cookie('salt', salt, 365*24*60*60)
    response.set_cookie('hash', hash, 365*24*60*60)
    return response


def main(request):

    visitor = _get_or_create_visitor(request)

    if request.method == 'POST':

        # We might have a token from the other server:

        encoded = request.POST['encoded']
        hashed = request.POST['hashed']

        other_t = base64.b64decode(encoded)
        this_t = time.time()

        delta = abs(int(other_t) - this_t)

        this_hash = _hash_helper(other_t)

        if (delta > (60*60*2)) or (hashed != this_hash):

            return render_to_response('auth_error.html', {}, RequestContext(request))

        else:

            salt = str(random.randrange(10000,10000000))
            hash = _hash_helper(salt)

            # Save User Data to Session
            if visitor:
                visitor.modx_id = request.POST['id']
                visitor.username = request.POST['username']
                visitor.fullname = request.POST['fullname']
                visitor.save()

            response = HttpResponseRedirect('/')
            response.set_cookie('salt', salt, 365*24*60*60)
            response.set_cookie('hash', hash, 365*24*60*60)
            return response
    
    return render_to_response("index.html", {
        'colleges': College.objects.all().order_by('school'),
        'occupations': DOLSalary.objects.all().order_by('occupation'),
        'draft_cells': DRAFT_CELLS,
        'positions': POSITIONS,
        'statuses': STATUSES
        }, RequestContext(request))


def output(request):

    college = int(request.POST['college'])
    alt = int(request.POST['alt'])
    sec = int(request.POST['sec'])
    pick = int(request.POST['pick'])
    pos = int(request.POST['pos'])
    status = int(request.POST['status'])

    m = AcefsModel(college=college, alt=alt, secondary=sec, expected_pick=pick, position=pos, status=status)

    visitor = _get_or_create_visitor(request)
    if visitor:
        scenario = Scenario()
        scenario.visitor = visitor
        scenario.college = m.college
        scenario.alt = m.alt
        scenario.sec = m.secondary
        scenario.pick = m.expected_pick.cell
        scenario.pos = m.position.index
        scenario.status = m.status.index
        scenario.save()

    if request.COOKIES.has_key('salt'):

        # We might have a cookie:
        salt = request.COOKIES.get('salt', '')
        hash = request.COOKIES.get('hash', '')

        if (hash != _hash_helper(salt)):
            return render_to_response('auth_error.html', {}, RequestContext(request))

    else:

        return render_to_response('auth_error.html', {}, RequestContext(request))


    if visitor:
        scenario.anonymous = False
        scenario.save()

    table = []
    for y in range(0, TOTAL_YEARS):
        table.append({
            'year': y + datetime.datetime.now().year,
            'pr_minors': m.pr_minors[y],
            'pr_out': m.pr_out[y]
        })

    this_year = datetime.datetime.now().year
    graph = [
        {
            'label': 'Earnings [Baseball]',
            'data': [[y + this_year, m.e_mlb[y]] for y in range(0, TOTAL_YEARS)],
            'color': '#009900'
        },
        {
            'label': 'Earnings [Alternate]',
            'data': [[y + this_year, m.e_alt[y]] for y in range(0, TOTAL_YEARS)],
            'color': '#CC0000'
        }

        ]

    years = [this_year + 2 * y + 1 for y in range(0, TOTAL_YEARS/2)]

    return render_to_response('output.html', {
        'model': m,
        'table': table,
        'graph': graph,
        'years': years
    }, RequestContext(request))

@staff_member_required
def visitors(request):
    return render_to_response('visitors.html', {
    }, RequestContext(request))

@staff_member_required
def visitor_list(request, page_num=1):

    # Annotate using number of scenarios and filter to show only > 0
    visitors = Visitor.objects.annotate(num_scenarios=Count('scenario'))
    visitors = visitors.filter(num_scenarios__gt=0)
    
    if request.GET.has_key('term'):
        term = request.GET['term']
        visitors = visitors.filter(fullname__icontains=term)

    else:
        term = ''
        visitors = visitors.all()

    paginator = Paginator(visitors, 20)
    page = paginator.page(int(page_num))

    return render_to_response('visitor_list.html', {
        'term': term,
        'page': page
    }, RequestContext(request))

@staff_member_required
def visitor_detail(request, visitor_id):
    return render_to_response('visitor_detail.html', {
        'visitor': Visitor.objects.get(pk=visitor_id)
    }, RequestContext(request))

acefs/templates/auth_error.html
{% load acefs_extras %}
{% load flatblock_tags %}

<div>

    {% flatblock 'autherror.text' 3600 %}

</div>


<div class="clear"></div>


<script type="text/javascript">

    function render_plot(){
    }

</script>

acefs/templates/base.html
{% load flatblock_tags %}

<html xmlns="http://www.w3.org/1999/xhtml">
<head>

    <title>{% flatblock 'site.title' 3600 %}</title>

    <link rel="stylesheet" type="text/css" href="http://mldraft.com/css/mlds.css" />

    <link rel="stylesheet" href="{{ MEDIA_URL }}/css/chosen.css" />

    <!--<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/jquery.ui.ufd-0.5/css/ufd-base.css" />-->
    <!--<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/jquery.ui.ufd-0.5/css/custom/custom.css" />-->

    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/css/jquery.jqplot.css" />

    <link rel="shortcut icon" href="http://mldraft.com/favicon.ico" />


    <style type="text/css">

        div.toprow div.select_container {
            width: 320px;
        }

        div.toprow {
            margin-top: 10px;    
        }

        div.toprow div.select_container select {
            width: 300px;
        }

        div.nav_links {
            color: #666;
        }

        div.nav_links a {
            border: none;
        }

        div.clear {
            clear: both;
        }

        div.app {
            margin-top: 15px;
            color: #000;
            background-color: #fff;
            border: 1px solid #666;
            padding: 15px;
            text-align: left;
        }

        label {
            float: left;
            margin-bottom: 15px;
            margin-right: 10px;
            }

        label.big {
            width: 320px;
            margin-right: 0px;
            margin-bottom: 5px;
        }

        div.select_container {
            float: left;
            margin-bottom: 15px;
        }

        select {
            margin-right: 30px;
        }

        select.chzn {
            width: 700px;
            margin-right: 0px;
        }

        div#button_container {
            margin-top: 20px;
            text-align: center;
        }

        button {
            width: 150px;
            height: 40px;
            font-size: 24px;
            color: green;
        }

        div.wide_column {
            float: left;
            width: 720px;
        }

        div.inner_column {
            float: left;
            width: 260px;
            margin-right: 0px;
            margin-bottom: 20px;
        }

        div.inner_column p {
            margin: 0px 0px 3px 0px;
            font-size: 12px;
        }

        div.inner_column p.big_num {
            font-size: 32px;
        }

        div.skinny_column {
            float: left;
        }

        div.skinny_column table {
            border: 1px solid #666;
            color: #000;
            font-size: 13px;
            border-collapse: collapse;
        }

        div.skinny_column table th {
            background-color: #fff;
            border-bottom: 1px solid #666;
            padding: 5px;
            margin: 0px;
        }

        div.skinny_column table td {
            padding: 2px 5px;
            text-align: right;
        }

        div.skinny_column table tr.even td {
            padding: 2px 5px;
            background-color: #ddd;
        }

        div.footer {
            font-family: Arial;
            font-size: 12px;
            margin-top: 40px;
            color: #666;
        }

        div.footer a:link,
        div.footer a:active,
        div.footer a:visited {
            color: #333;
        }

        div.footer a:hover {
            color: #339;
        }

        .red {
            color: #C00;
        }

        .green {
            color: #090;
        }

        .note {
            color: #666;
        }

        div#throbber {
            text-align: center;
            margin: 30px auto;
        }

        div#chart_title {
            margin: 0px 0px 10px 0px;
            text-align: center;
            font-size: 18px;
        }

        div#consistency_warning {
            margin: 5px 5px 20px 5px;
            border: 2px solid #CC0;
            background-color: #FF6;
            padding: 5px 10px;
        }

        #tooltip {
            position: absolute;
            z-index: 3000;
            border: 1px solid #FF6;
            background-color: #ffff8f;
            padding: 5px 15px;
            opacity: 0.90;
            color: #333;
            font-size: 13px;
            font-weight: normal;
        }
        #tooltip h3, #tooltip div { margin: 0; font-weight: normal;}

        div#help_text {
            float: left;
            margin-top: 24px;
            color: #000;
            padding: 5px 8px;
            border: 1px solid #ffcc00;
            background-color: #FFFF8F;
        }

        div.career p {
            font-size: 14px;
        }

    </style>

    {% block header_style %}{% endblock %}

</head>
<body>

<center>
<div id="wrapper">

    <div id="header">
        <div class="banner">
            <a href="http://members.mldraft.com"><img src="http://mldraft.com/images/banner.jpg" border="0"></a>
        </div>

        <div class="clear"></div>

    </div>

    <div class="clear"></div>

    {% block content %}{% endblock %}


    <div class="footer">

        {% flatblock 'site.copyright' 3600 %} Web App by <a href="http://brooklynsoftworks.com">Brooklyn Softworks</a>.

    </div>

</div>
</center>

</body>
</html>

acefs/templates/output.html
{% load acefs_extras %}
{% load flatblock_tags %}

<div class="inner_column" style="width: 200px;">

    <p class="tip" title="{% flatblock 'output.bonus_threshold.help' 3600 %}">
        {% flatblock 'output.bonus_threshold.label' 3600 %}
    </p>
    <p class="big_num tip" title="{% flatblock 'output.bonus_threshold.help' 3600 %}">{{ model.bonus_threshold|currency }}</p>

</div>

<div class="inner_column" style="width: 240px;">

    <p class="tip" title="{% flatblock 'output.max_slotted_bonus.help' 3600 %}">
        {% flatblock 'output.max_slotted_bonus.label' 3600 %}
    </p>
    <p class="big_num tip" title="{% flatblock 'output.max_slotted_bonus.help' 3600 %}">{{ model.max_slotted_bonus|currency }}</p>

</div>

<div class="inner_column" style="width: 240px;">

    <p>
        {% flatblock 'output.best_path.label' 3600 %}
    </p>
    {% if model.play_ball %}
        <p class="big_num green">{% flatblock 'output.best_path.baseball' 3600 %}</p>
    {% else %}
        <p class="big_num red">{% flatblock 'output.best_path.alternate' 3600 %}</p>
    {% endif %}

</div>


<div class="inner_column career" style="width: 240px;">

    <p class="tip" title="{% flatblock 'output.mlb_avg.help' 3600 %}">{% flatblock 'output.mlb_avg.label' 3600 %} <b>{{  model.MLBAverage }}</b></p>
    <p class="tip" title="{% flatblock 'output.milb_avg.help' 3600 %}">{% flatblock 'output.milb_avg.label' 3600 %} <b>{{  model.MiLBAverage }}</b></p>
    <p class="tip" title="{% flatblock 'output.pr_mlb.help' 3600 %}">{% flatblock 'output.pr_mlb.label' 3600 %} <b>{{  model.pr_mlb|percentage }}</b></p>

</div>

<div class="clear"></div>

<div class="wide_column">

    <div id="chart_title">{% flatblock 'output.chart.title' 3600 %}</div>
    <div id="chart" style="height:350px; width:700px;" class="tip" title="{% flatblock 'output.chart.help' 3600 %}"></div>
    <p class="note"><i>{% flatblock 'output.chart.note' 3600 %}</i></p>

</div>

<div class="skinny_column">
    <table>
        <thead>
            <tr>
                <th>{% flatblock 'output.table.year.label' 3600%}</th>
                <th class="tip" title="{% flatblock 'output.table.pr_minors.help' 3600 %}">{% flatblock 'output.table.pr_minors.label' 3600 %}</th>
                <th class="tip" title="{% flatblock 'output.table.pr_out.help' 3600 %}">{% flatblock 'output.table.pr_out.label' 3600 %}</th>
            </tr>
        </thead>
        <tbody>
            {% for row in table %}
            <tr class="{% if forloop.counter|divisibleby:2 %}even{% else %}odd{% endif %}">
                <td>{{ row.year }}</td>
                <td>{{ row.pr_minors|percentage }}</td>
                <td>{{ row.pr_out|percentage }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


<div class="clear"></div>


<script type="text/javascript">

    function render_plot(){

        $('.tip').tooltip();

        $.plot(('#chart'), {{ graph|safe }}, {

            series: {
                lines: { show:  true },
                points: { show: true }
            },
            xaxis: {
                label: 'Years',
                ticks: {{  years }},
                tickFormatter: function numberWithCommas(x) {
                    return x.toString();
                }
            },
            yaxis: {
                label: 'Salary',
                tickFormatter: function numberWithCommas(x) {
                    return '$' + x.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g, ",");
                }
            }

        });

    }


</script>

acefs/templates/visitor_detail.html
<h3>{{ visitor.fullname }}</h3>

<p>
    ModX: {{ visitor.username }},
        {% if visitor.modx_id %}
        <a href="http://mldraft.com/manager/index.php?a=34&id={{ visitor.modx_id }}">Profile</a>
    {% else %}
        Profile Not Available
    {% endif %}
</p>

<p class="tech">
    {{ visitor.ip }}
    <br/>{{ visitor.user_agent }}
</p>

<table>
    <thead>
        <tr>
            <th>Timestamp</th>
            <th>College</th>
            <th>Careers</th>
            <th>Pick</th>
            <th>Position</th>
            <th>Status</th>
            <th>Trial</<th>
        </tr>
    </thead>
    <tbody>
        {% for s in visitor.scenario_set.all %}
        <tr class="scenario_row"
            val_college="{{ s.college.id }}"
            val_alt="{{ s.alt.id }}"
            val_sec="{{ s.sec.id }}"
            val_pick="{{ s.pick }}"
            val_pos="{{ s.pos }}"
            val_status="{{ s.status }}"
            val_anonymous="{{ s.anonymous }}"
            >
            <td>{{ s.timestamp }}</td>
            <td>{{ s.college }}</td>
            <td><i>alt</i> {{ s.alt }}
                <br/><i>sec</i> {{ s.sec }}</td>
            <td>{{ s.get_draft_cell }}</td>
            <td>{{ s.get_position }}</td>
            <td>{{ s.get_status }} / {{ s.status }}</td>
            <td>{% if  s.anonymous  %}Trial{% else %}Paid{% endif %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

acefs/templates/visitor_list.html
<p>
    <input id="txt_search" type="text" value="{{ term }}" /> <button id="btn_search">Search</button>
    <br>(<a href="/visitor_list/1">Clear Search</a>)
</p>


<p>
    Page {{ page.number }} of {{ page.paginator.num_pages }}
    {% if page.has_previous %}<a href="/visitor_list/{{ page.previous_page_number }}">Previous</a>{% endif %}
    {% if page.has_next %}<a href="/visitor_list/{{ page.next_page_number }}">Next</a>{% endif %}
</p>

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Full Name</th>
            <th>Scenarios</th>
        </tr>
    </thead>
    {% for v in page.object_list %}
    <tbody>
        <tr>
            <td class="count"><span class="visitor_id">{{ v.id }}</span></td>
            <td>{{ v.fullname }}</td>
            <td class="count">{{ v.num_scenarios }}</td>
        </tr>
    </tbody>
    {% endfor %}

</table>